package com.sap.cloud.sdk;

import com.google.gson.Gson;
import com.sap.cloud.sdk.cloudplatform.connectivity.DestinationAccessor;
import com.sap.cloud.sdk.odatav2.connectivity.ODataException;
import com.sap.cloud.sdk.s4hana.connectivity.DefaultErpHttpDestination;
import com.sap.cloud.sdk.s4hana.connectivity.ErpHttpDestination;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;

// generated by SAP Cloud SDK VDM generator
import com.vdm.namespaces.bank.Bank;
import com.vdm.services.DefaultBankService;

@WebServlet("/bank")
public class GetBankServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    private static final Logger logger = LoggerFactory.getLogger(GetBankServlet.class);
    private static final ErpHttpDestination destination =
            DestinationAccessor.getDestination("Erp1809")
                    .asHttp().decorate(DefaultErpHttpDestination::new);

    @Override
    protected void doGet(final HttpServletRequest request, final HttpServletResponse response)
            throws IOException {

        logger.info("Start get method: " + request.getRequestURI());

        try{
            final List<Bank> banks =
                    new DefaultBankService()
                            .getAllBank()
                            .select(Bank.BANK_KEY, Bank.BANK_NAME)
                            .filter(Bank.BANK_COUNTRY.eq("JP"))
                            .top(5)
                            .execute(destination);
            logger.info(new Gson().toJson(banks));
            response.setContentType("application/json");
            response.setCharacterEncoding("UTF-8");
            response.getWriter().write(new Gson().toJson(banks));

        } catch (final ODataException e){
            logger.error(e.getMessage(), e);
            response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
            response.getWriter().write(e.getMessage());
        }
    }
}
